"use client";
import type { Metadata } from "next";
import { M_PLUS_1 } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/hooks/auth";
import { CartProvider } from "@/hooks/cart";
import { Provider } from "react-redux";
import store from "@/store";

const m_plus = M_PLUS_1({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${m_plus.className} antialiased bg-bgPages text-white`}>
        <Provider store={store}>
          <AuthProvider>
            <CartProvider>
              <main>{children}</main>
              <Toaster />
            </CartProvider>
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
